// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUW1m0CVMRv6hWa47DgcY4f76j2GFxm7c',
    appId: '1:915680487540:web:fc420fd1b695b36dd70921',
    messagingSenderId: '915680487540',
    projectId: 'chatapp-a4b5f',
    authDomain: 'chatapp-a4b5f.firebaseapp.com',
    storageBucket: 'chatapp-a4b5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCufJHlIYOglHjxMc4oE8EEKYr1izyzcNk',
    appId: '1:915680487540:android:2de0e3a1db5c19f1d70921',
    messagingSenderId: '915680487540',
    projectId: 'chatapp-a4b5f',
    storageBucket: 'chatapp-a4b5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAevMfbOzF8pgyIS9mX2guXwsmshGov_Q0',
    appId: '1:915680487540:ios:aadffe18d7535569d70921',
    messagingSenderId: '915680487540',
    projectId: 'chatapp-a4b5f',
    storageBucket: 'chatapp-a4b5f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAevMfbOzF8pgyIS9mX2guXwsmshGov_Q0',
    appId: '1:915680487540:ios:aadffe18d7535569d70921',
    messagingSenderId: '915680487540',
    projectId: 'chatapp-a4b5f',
    storageBucket: 'chatapp-a4b5f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUW1m0CVMRv6hWa47DgcY4f76j2GFxm7c',
    appId: '1:915680487540:web:9e503d2aeb9fa5ebd70921',
    messagingSenderId: '915680487540',
    projectId: 'chatapp-a4b5f',
    authDomain: 'chatapp-a4b5f.firebaseapp.com',
    storageBucket: 'chatapp-a4b5f.appspot.com',
  );
}